%%% SETS PARAMETERS TO DRAW PHASE PORTRAITE
% NPDSToolbox version 1.0.0
% handles    Structure with handles and user data (see GUIDATA)

%   This code sends model parameters to the Portraite function (see Portraite(..))
%   according to the selected model.


% For information about the parameters of the models
%, refer to the parameters guide (PARAMETER_GUIDE.md)


function PortraiteDynamic(handles)
contents = get(handles.Popup_Neuron,'String');
val = contents{get(handles.Popup_Neuron,'Value')};
if strcmp(val,'Hudgkin-Huxley')
    Portraite(handles,handles.Axes_Phase,[get(handles.Check_port1,'value'),get(handles.Check_port2,'value'),get(handles.Check_port3,'value'),get(handles.Check_port4,'value')],1,...
        get(handles.Slider_initcond1,'value'),get(handles.Slider_initcond2,'value'),...
        get(handles.Slider_initcond3,'value'),get(handles.Slider_initcond4,'value'),...
        get(handles.Slider_exter_current,'value'),...
        str2double(get(handles.EditHHvNa,'String')),...
        str2double(get(handles.EditHHvK,'String')),str2double(get(handles.EditHHvL,'String')),...
        str2double(get(handles.EditHHgNa,'String')),str2double(get(handles.EditHHgK,'String')),...
        str2double(get(handles.EditHHgL,'String')),str2double(get(handles.EditHHC,'String')),...
        str2double(get(handles.Time_edit,'string')));
elseif strcmp(val,'FihzHugh-Nagumo')
    
    Portraite(handles,handles.Axes_Phase,[1,1,0,0],2,get(handles.Slider_initcond1,'value'),get(handles.Slider_initcond2,'value'),...
        get(handles.Slider_exter_current,'value'),str2double(get(handles.EditFHNa,'String')),...
        str2double(get(handles.EditFHNb,'String')),str2double(get(handles.EditFHNc,'String')),...
        str2double(get(handles.Time_edit,'string')));
elseif strcmp(val,'Rose-Hindmarsh')
    Portraite(handles,handles.Axes_Phase,[get(handles.Check_port1,'value'),get(handles.Check_port2,'value'),get(handles.Check_port3,'value'),0],3,...
        get(handles.Slider_initcond1,'value'),get(handles.Slider_initcond2,'value'),get(handles.Slider_initcond3,'value'),...
        get(handles.Slider_exter_current,'value'),str2double(get(handles.EditRHa,'String')),...
        str2double(get(handles.EditRHb,'String')),str2double(get(handles.EditRHc,'String')),...
        str2double(get(handles.EditRHd,'String')),str2double(get(handles.EditRHr,'String')),str2double(get(handles.EditRHs,'String')),str2double(get(handles.EditRHXr,'String')),...
        str2double(get(handles.Time_edit,'string')));
elseif strcmp(val,'Thalamic')
    Portraite(handles,handles.Axes_Phase,[get(handles.Check_port1,'value'),get(handles.Check_port2,'value'),get(handles.Check_port3,'value'),0],4,...
        get(handles.Slider_initcond1,'value'),get(handles.Slider_initcond2,'value'),get(handles.Slider_initcond3,'value'),...
        get(handles.Slider_exter_current,'value'),str2double(get(handles.EditTeNa,'String')),...
        str2double(get(handles.EditTeK,'String')),str2double(get(handles.EditTeL,'String')),...
        str2double(get(handles.EditTeT,'String')),str2double(get(handles.EdirTgNa,'String')),...
        str2double(get(handles.EditTgK,'String')),str2double(get(handles.EditTgL,'String')),str2double(get(handles.EditTgT,'String')),str2double(get(handles.EditTeC,'String')),...
        str2double(get(handles.Time_edit,'string')));
end

